spring.application.name=olive-backend
spring.data.mongodb.uri=mongodb://localhost:27017/olive_db
spring.data.mongodb.database=olive_db
server.port=8080

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.cooperative.olive=DEBUG

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rayenchaaben0704@gmail.com
spring.mail.password=vkht ytya aqmp obxp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Application specific email settings
app.mail.from=rayenchaaben0704@gmail.com
app.mail.reset.subject=Reinitialisation de votre mot de passe - CoopOleicole

# Cloudinary
cloudinary.cloud-name=dcdaqdxj2
cloudinary.api-key=228841716467458
cloudinary.api-secret=_S9-5MjJnGRV0Tt25xWCHKtzm0Q
