spring.application.name=olive-backend
spring.data.mongodb.uri=mongodb://localhost:27017/olive_db
spring.data.mongodb.database=olive_db
server.port=8080

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.cooperative.olive=DEBUG
